### ISSUE TITLE
Add SyGMa node to 3d-eChem-VM

### ISSUE THREAD

**Issue by ridderl** [3D-e-Chem/knime-sygma#10]
After a fresh install of the VM I don't have the SyGMa node.

**Comment by sverhoeven** [comment]
Can you check which version of the 3D-e-Chem vagrant base box you have with `vagrant box list`?

It should return something like:
```
nlesc/3d-e-chem                     (virtualbox, 1.2.1)
```

Your version is probably lower. Please follow the instructions at https://github.com/3D-e-Chem/3D-e-Chem-VM/wiki/Software#upgrading to either recreate the VM based on the latest box or upgrade the VM.

**Comment by sverhoeven** [comment]
SyGMA was added in version 1.2.0 of the 3D-e-Chem vagrant base box.

**Comment by ridderl** [comment]
Ah, for some reason I'm still on `nlesc/3d-e-chem                     (virtualbox, 1.1.1)`. I'm now trying `vagrant box update --box nlesc/3d-e-chem`

**Comment by ridderl** [comment]
Should the `vagrant box update --box nlesc/3d-e-chem` command also be mentioned in the paper? I think with the init command you just get 1.1.1 ?

**Comment by sverhoeven** [comment]
The first time `vagrant up` is run after a `vagrant init nlesc/3d-e-chem`, vagrant will download the latest 3d-e-chem box at that time. Any vagrant VMs created later will use that box. So if you had deleted the box before doing a `vagrant up` you should have gotten the v1.2.1 version.

I think it will make the paper go into too much technical detail, giving multiple ways to accomplish an update. Also if the web server was up, the vagrant_upgrade command would have worked OK. So what is in the paper is correct, but just not comprehensive.

**Comment by ridderl** [comment]
Agreed, thanks for clarifying.
