### ISSUE TITLE
Installation fails with latest KNIME Nightly

### ISSUE THREAD

**Issue by danielesser** [3D-e-Chem/knime-sygma#16]
We are not able to install the Sygma KNIME Nodes with the latest KNIME nightly version starting Oct 31st, 2020. I assume KNIME has removed some features from its nightly update site, this plugin is requiring, e.g. `org.knime.core [3.1.0,4.0.0)'`.

More concrete, during installation, we get the following error:

```
Cannot complete the install because one or more required items could not be found.
        Software being installed: Sygma KNIME nodes 1.2.1.v201906271207 (nl.esciencecenter.e3dchem.sygma.feature.feature.group 1.2.1.v201906271207)
        Missing requirement: Abstract Python wrapper KNIME node and helpers 2.0.1.v201802071345 (nl.esciencecenter.e3dchem.python.plugin 2.0.1.v201802071345) requires 'osgi.bundle; org.knime.core [3.1.0,4.0.0)' but it could not be found
        Missing requirement: Abstract Python wrapper KNIME node and helpers 2.0.2.v201906270941 (nl.esciencecenter.e3dchem.python.plugin 2.0.2.v201906270941) requires 'osgi.bundle; org.knime.python2.serde.arrow.libs [4.0.0,5.0.0)' but it could not be found
        Missing requirement: Abstract Python wrapper KNIME node and helpers 2.0.3.v201907021159 (nl.esciencecenter.e3dchem.python.plugin 2.0.3.v201907021159) requires 'osgi.bundle; org.knime.python2.serde.arrow.libs [4.0.0,5.0.0)' but it could not be found
        Cannot satisfy dependency:
                From: Sygma KNIME nodes 1.2.1.v201906271207 (nl.esciencecenter.e3dchem.sygma.feature.feature.group 1.2.1.v201906271207)
                To: org.eclipse.equinox.p2.iu; nl.esciencecenter.e3dchem.sygma.plugin [1.2.1.v201906271207,1.2.1.v201906271207]
        Cannot satisfy dependency:
                From: Sygma KNIME nodes 1.2.1.v201906271207 (nl.esciencecenter.e3dchem.sygma.plugin 1.2.1.v201906271207)
                To: osgi.bundle; nl.esciencecenter.e3dchem.python.plugin [2.0.1,3.0.0)
```

**Comment by sverhoeven** [comment]
The Sygma nodes indirectly use https://github.com/knime/knime-python/ , which has changed the API in since 4.3.0. 

I started working at adding KNIME 4.3 support in https://github.com/3D-e-Chem/knime-python-wrapper/pull/9, after that is fixed I should be able to make a new version of the Sygma nodes.

**Comment by danielesser** [comment]
Hey Stefan. Is there any update on this?

**Comment by sverhoeven** [comment]
Started on PR https://github.com/3D-e-Chem/knime-sygma/pull/17 . I am able to run the node when I build + install it locally, but tests are failing. 

My allotted time is up so need find some more time to work on it again later.

**Comment by sverhoeven** [comment]
A new version has been released that fixes the problem. You should be able to install 3D-e-Chem nodes v1.6.0 from KNIME Community Extensions (https://update.knime.com/community-contributions/4.3) update site or from https://3d-e-chem.github.io/knime-node-collection/4.3/ if community extensions is not yet updated.

**Comment by danielesser** [comment]
Thanks for the head-up and fix, Stefan! 👍
